//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Xml.Linq;
using System.Xml.Serialization;
using Qujck.Pas.Core.Enumerations;
using Qujck.Pas.Model.Policy.DataObjects;

namespace Qujck.Pas.Model.Policy
{
    [Serializable]
    public sealed partial class Address : AbstractPolicyEntity
    {
        internal AddressDo initialValues { get; private set; }
        internal AddressDo updatedValues { get; private set; }
        internal Action<AddressDo, string> loadMissingValue { private get; set; }

        public Address()
        {
            this.initialValues = new AddressDo();
            this.updatedValues = new AddressDo();
            this.loadMissingValue = (a, b) => { };
        }

        [XmlIgnore]
        internal override string schema
        {
            get
            {
                return "Policy";
            }
        }

        [XmlIgnore]
        internal override string table
        {
            get
            {
                return "Address";
            }
        }

        [XmlIgnore]
        internal override IEnumerable<string> columns
        {
            get
            {
                yield return "id";
                yield return "addressLine1";
                yield return "addressLine2";
                yield return "addressLine3";
                yield return "addressLine4";
                yield return "postcode";
                yield return "country";
            }
        }

        public override long id
        {
            get
            {
                return this.initialValues.id;
            }
            set
            {
                this.initialValues.id = value;
            }
        }

        [StringLength(35)]
        [XmlElement(ElementName="addressLine1")]
        public string addressLine1 
	    { 
            get
            {
                if (this.updatedValues.addressLine1HasValue)
                {
                    return this.updatedValues.addressLine1;
                }
                
                if (!this.initialValues.addressLine1HasValue)
                {
                    this.loadMissingValue(this.initialValues, "addressLine1");
                    this.initialValues.addressLine1HasValue = true;
                }

                return this.initialValues.addressLine1;
            }
            set
            {
                this.updatedValues.addressLine1 = value;
            }
        }

        [StringLength(35)]
        [XmlElement(ElementName="addressLine2")]
        public string addressLine2 
	    { 
            get
            {
                if (this.updatedValues.addressLine2HasValue)
                {
                    return this.updatedValues.addressLine2;
                }
                
                if (!this.initialValues.addressLine2HasValue)
                {
                    this.loadMissingValue(this.initialValues, "addressLine2");
                    this.initialValues.addressLine2HasValue = true;
                }

                return this.initialValues.addressLine2;
            }
            set
            {
                this.updatedValues.addressLine2 = value;
            }
        }

        [StringLength(35)]
        [XmlElement(ElementName="addressLine3")]
        public string addressLine3 
	    { 
            get
            {
                if (this.updatedValues.addressLine3HasValue)
                {
                    return this.updatedValues.addressLine3;
                }
                
                if (!this.initialValues.addressLine3HasValue)
                {
                    this.loadMissingValue(this.initialValues, "addressLine3");
                    this.initialValues.addressLine3HasValue = true;
                }

                return this.initialValues.addressLine3;
            }
            set
            {
                this.updatedValues.addressLine3 = value;
            }
        }

        [StringLength(35)]
        [XmlElement(ElementName="addressLine4")]
        public string addressLine4 
	    { 
            get
            {
                if (this.updatedValues.addressLine4HasValue)
                {
                    return this.updatedValues.addressLine4;
                }
                
                if (!this.initialValues.addressLine4HasValue)
                {
                    this.loadMissingValue(this.initialValues, "addressLine4");
                    this.initialValues.addressLine4HasValue = true;
                }

                return this.initialValues.addressLine4;
            }
            set
            {
                this.updatedValues.addressLine4 = value;
            }
        }

        [StringLength(50)]
        [RegularExpression(@"[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z-[CIKMOV]]{2}|(BFPO \d{1,4})")]
        [XmlElement(ElementName="postcode")]
        public string postcode 
	    { 
            get
            {
                if (this.updatedValues.postcodeHasValue)
                {
                    return this.updatedValues.postcode;
                }
                
                if (!this.initialValues.postcodeHasValue)
                {
                    this.loadMissingValue(this.initialValues, "postcode");
                    this.initialValues.postcodeHasValue = true;
                }

                return this.initialValues.postcode;
            }
            set
            {
                this.updatedValues.postcode = value;
            }
        }

        [StringLength(35)]
        [XmlElement(ElementName="country")]
        public string country 
	    { 
            get
            {
                if (this.updatedValues.countryHasValue)
                {
                    return this.updatedValues.country;
                }
                
                if (!this.initialValues.countryHasValue)
                {
                    this.loadMissingValue(this.initialValues, "country");
                    this.initialValues.countryHasValue = true;
                }

                return this.initialValues.country;
            }
            set
            {
                this.updatedValues.country = value;
            }
        }

        partial void BeforeDeserialize(IQueryable<XElement> elements);
        partial void AfterDeserialize(IQueryable<XElement> elements);

        public override void Deserialize(IQueryable<XElement> elements)
        {
            this.BeforeDeserialize(elements);

            XElement e1 = elements.FirstOrDefault(x => x.Name == "id");
            if (e1 != null)
            {
                this.id = long.Parse(e1.Value);
            }

            XElement e2 = elements.FirstOrDefault(x => x.Name == "addressLine1");
            if (e2 != null) 
            {
                this.addressLine1 = e2.Value;
            }

            XElement e3 = elements.FirstOrDefault(x => x.Name == "addressLine2");
            if (e3 != null) 
            {
                this.addressLine2 = e3.Value;
            }

            XElement e4 = elements.FirstOrDefault(x => x.Name == "addressLine3");
            if (e4 != null) 
            {
                this.addressLine3 = e4.Value;
            }

            XElement e5 = elements.FirstOrDefault(x => x.Name == "addressLine4");
            if (e5 != null) 
            {
                this.addressLine4 = e5.Value;
            }

            XElement e6 = elements.FirstOrDefault(x => x.Name == "postcode");
            if (e6 != null) 
            {
                this.postcode = e6.Value;
            }

            XElement e7 = elements.FirstOrDefault(x => x.Name == "country");
            if (e7 != null) 
            {
                this.country = e7.Value;
            }

            this.AfterDeserialize(elements);
        }

        partial void BeforeWriteXml(System.Xml.XmlWriter writer);
        partial void AfterWriteXml(System.Xml.XmlWriter writer);

        public override void WriteXml(System.Xml.XmlWriter writer)
        {
            this.BeforeWriteXml(writer);

            writer.WriteElementString("id", this.initialValues.id.ToString());

            if (this.updatedValues.addressLine1HasValue && !string.IsNullOrEmpty(addressLine1))
            {
                writer.WriteElementString("addressLine1", this.updatedValues.addressLine1);
            }
            else if (this.initialValues.addressLine1HasValue && !string.IsNullOrEmpty(addressLine1))
            {
                writer.WriteElementString("addressLine1", this.initialValues.addressLine1);
            }

            if (this.updatedValues.addressLine2HasValue && !string.IsNullOrEmpty(addressLine2))
            {
                writer.WriteElementString("addressLine2", this.updatedValues.addressLine2);
            }
            else if (this.initialValues.addressLine2HasValue && !string.IsNullOrEmpty(addressLine2))
            {
                writer.WriteElementString("addressLine2", this.initialValues.addressLine2);
            }

            if (this.updatedValues.addressLine3HasValue && !string.IsNullOrEmpty(addressLine3))
            {
                writer.WriteElementString("addressLine3", this.updatedValues.addressLine3);
            }
            else if (this.initialValues.addressLine3HasValue && !string.IsNullOrEmpty(addressLine3))
            {
                writer.WriteElementString("addressLine3", this.initialValues.addressLine3);
            }

            if (this.updatedValues.addressLine4HasValue && !string.IsNullOrEmpty(addressLine4))
            {
                writer.WriteElementString("addressLine4", this.updatedValues.addressLine4);
            }
            else if (this.initialValues.addressLine4HasValue && !string.IsNullOrEmpty(addressLine4))
            {
                writer.WriteElementString("addressLine4", this.initialValues.addressLine4);
            }

            if (this.updatedValues.postcodeHasValue && !string.IsNullOrEmpty(postcode))
            {
                writer.WriteElementString("postcode", this.updatedValues.postcode);
            }
            else if (this.initialValues.postcodeHasValue && !string.IsNullOrEmpty(postcode))
            {
                writer.WriteElementString("postcode", this.initialValues.postcode);
            }

            if (this.updatedValues.countryHasValue && !string.IsNullOrEmpty(country))
            {
                writer.WriteElementString("country", this.updatedValues.country);
            }
            else if (this.initialValues.countryHasValue && !string.IsNullOrEmpty(country))
            {
                writer.WriteElementString("country", this.initialValues.country);
            }

            this.AfterWriteXml(writer);
        }
    }
}
