//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Xml.Linq;
using System.Xml.Serialization;
using Qujck.Pas.Core.Enumerations;
using Qujck.Pas.Model.Policy.DataObjects;

namespace Qujck.Pas.Model.Policy
{
    [Serializable]
    public sealed partial class Party_Address : AbstractPolicyEntity
    {
        internal Party_AddressDo initialValues { get; private set; }
        internal Party_AddressDo updatedValues { get; private set; }
        internal Action<Party_AddressDo, string> loadMissingValue { private get; set; }

        public Party_Address()
        {
            this.initialValues = new Party_AddressDo();
            this.updatedValues = new Party_AddressDo();
            this.loadMissingValue = (a, b) => { };
        }

        [XmlIgnore]
        internal override string schema
        {
            get
            {
                return "Policy";
            }
        }

        [XmlIgnore]
        internal override string table
        {
            get
            {
                return "Party_Address";
            }
        }

        [XmlIgnore]
        internal override IEnumerable<string> columns
        {
            get
            {
                yield return "id";
                yield return "type";
                yield return "preferred";
                yield return "termInResidence";
                yield return "goneAway";
                yield return "Party_id";
                yield return "Address_id";
            }
        }

        public override long id
        {
            get
            {
                return this.initialValues.id;
            }
            set
            {
                this.initialValues.id = value;
            }
        }

        [XmlElement(ElementName="type")]
        public AddressType type 
	    { 
            get
            {
                if (this.updatedValues.typeHasValue)
                {
                    return this.updatedValues.type;
                }
                
                if (!this.initialValues.typeHasValue)
                {
                    this.loadMissingValue(this.initialValues, "type");
                    this.initialValues.typeHasValue = true;
                }

                return this.initialValues.type;
            }
            set
            {
                this.updatedValues.type = value;
            }
        }

        [RegularExpression(@"[YN]{1}")]
        [XmlElement(ElementName="preferred")]
        public Indicator preferred 
	    { 
            get
            {
                if (this.updatedValues.preferredHasValue)
                {
                    return this.updatedValues.preferred;
                }
                
                if (!this.initialValues.preferredHasValue)
                {
                    this.loadMissingValue(this.initialValues, "preferred");
                    this.initialValues.preferredHasValue = true;
                }

                return this.initialValues.preferred;
            }
            set
            {
                this.updatedValues.preferred = value;
            }
        }

        [XmlElement(ElementName="termInResidence")]
        public short? termInResidence 
	    { 
            get
            {
                if (this.updatedValues.termInResidenceHasValue)
                {
                    return this.updatedValues.termInResidence;
                }
                
                if (!this.initialValues.termInResidenceHasValue)
                {
                    this.loadMissingValue(this.initialValues, "termInResidence");
                    this.initialValues.termInResidenceHasValue = true;
                }

                return this.initialValues.termInResidence;
            }
            set
            {
                this.updatedValues.termInResidence = value;
            }
        }

        [RegularExpression(@"[YN]{1}")]
        [XmlElement(ElementName="goneAway")]
        public Indicator goneAway 
	    { 
            get
            {
                if (this.updatedValues.goneAwayHasValue)
                {
                    return this.updatedValues.goneAway;
                }
                
                if (!this.initialValues.goneAwayHasValue)
                {
                    this.loadMissingValue(this.initialValues, "goneAway");
                    this.initialValues.goneAwayHasValue = true;
                }

                return this.initialValues.goneAway;
            }
            set
            {
                this.updatedValues.goneAway = value;
            }
        }

        [XmlElement(ElementName="Party_id")]
        public long Party_id 
	    { 
            get
            {
                if (this.updatedValues.Party_idHasValue)
                {
                    return this.updatedValues.Party_id;
                }
                
                if (!this.initialValues.Party_idHasValue)
                {
                    this.loadMissingValue(this.initialValues, "Party_id");
                    this.initialValues.Party_idHasValue = true;
                }

                return this.initialValues.Party_id;
            }
            set
            {
                this.updatedValues.Party_id = value;
            }
        }

        [XmlElement(ElementName="Address_id")]
        public long Address_id 
	    { 
            get
            {
                if (this.updatedValues.Address_idHasValue)
                {
                    return this.updatedValues.Address_id;
                }
                
                if (!this.initialValues.Address_idHasValue)
                {
                    this.loadMissingValue(this.initialValues, "Address_id");
                    this.initialValues.Address_idHasValue = true;
                }

                return this.initialValues.Address_id;
            }
            set
            {
                this.updatedValues.Address_id = value;
            }
        }

        public bool AddressIsLoaded { get; private set; }
        internal Func<Address> AddressQuery { private get; set; }
        public Address Address
        {
            get
            {
                if (this.AddressQuery == null)
                {
                    return null;
                }
                else
                {
                    var result = this.AddressQuery();
                    if (!this.AddressIsLoaded)
                    {
                        this.AddressIsLoaded = result != null;
                    }

                    return result;
                }
            }
        }

        public bool PartyIsLoaded { get; private set; }
        internal Func<Party> PartyQuery { private get; set; }
        public Party Party
        {
            get
            {
                if (this.PartyQuery == null)
                {
                    return null;
                }
                else
                {
                    var result = this.PartyQuery();
                    if (!this.PartyIsLoaded)
                    {
                        this.PartyIsLoaded = result != null;
                    }

                    return result;
                }
            }
        }

        partial void BeforeDeserialize(IQueryable<XElement> elements);
        partial void AfterDeserialize(IQueryable<XElement> elements);

        public override void Deserialize(IQueryable<XElement> elements)
        {
            this.BeforeDeserialize(elements);

            XElement e1 = elements.FirstOrDefault(x => x.Name == "id");
            if (e1 != null)
            {
                this.id = long.Parse(e1.Value);
            }

            XElement e2 = elements.FirstOrDefault(x => x.Name == "type");
            if (e2 != null)
            {
                this.type = e2.Value;
            }

            XElement e3 = elements.FirstOrDefault(x => x.Name == "preferred");
            if (e3 != null)
            {
                this.preferred = e3.Value;
            }

            XElement e4 = elements.FirstOrDefault(x => x.Name == "termInResidence");
            if (e4 != null)
            {
                this.termInResidence = short.Parse(e4.Value);
            }

            XElement e5 = elements.FirstOrDefault(x => x.Name == "goneAway");
            if (e5 != null)
            {
                this.goneAway = e5.Value;
            }

            XElement e6 = elements.FirstOrDefault(x => x.Name == "Party_id");
            if (e6 != null)
            {
                this.Party_id = long.Parse(e6.Value);
            }

            XElement e7 = elements.FirstOrDefault(x => x.Name == "Address_id");
            if (e7 != null)
            {
                this.Address_id = long.Parse(e7.Value);
            }

            this.AfterDeserialize(elements);
        }

        partial void BeforeWriteXml(System.Xml.XmlWriter writer);
        partial void AfterWriteXml(System.Xml.XmlWriter writer);

        public override void WriteXml(System.Xml.XmlWriter writer)
        {
            this.BeforeWriteXml(writer);

            writer.WriteElementString("id", this.initialValues.id.ToString());

            if (this.updatedValues.typeHasValue && type != AddressType.Null)
            {
                writer.WriteElementString("type", this.updatedValues.type.Value);
            }
            else if (this.initialValues.typeHasValue && type != AddressType.Null)
            {
                writer.WriteElementString("type", this.initialValues.type.Value);
            }

            if (this.updatedValues.preferredHasValue && preferred != Indicator.Null)
            {
                writer.WriteElementString("preferred", this.updatedValues.preferred.Value);
            }
            else if (this.initialValues.preferredHasValue && preferred != Indicator.Null)
            {
                writer.WriteElementString("preferred", this.initialValues.preferred.Value);
            }

            if (this.updatedValues.termInResidenceHasValue && termInResidence != null)
            {
                writer.WriteElementString("termInResidence", this.updatedValues.termInResidence.ToString());
            }
            else if (this.initialValues.termInResidenceHasValue && termInResidence != null)
            {
                writer.WriteElementString("termInResidence", this.initialValues.termInResidence.ToString());
            }

            if (this.updatedValues.goneAwayHasValue && goneAway != Indicator.Null)
            {
                writer.WriteElementString("goneAway", this.updatedValues.goneAway.Value);
            }
            else if (this.initialValues.goneAwayHasValue && goneAway != Indicator.Null)
            {
                writer.WriteElementString("goneAway", this.initialValues.goneAway.Value);
            }

            if (this.updatedValues.Party_idHasValue)
            {
                writer.WriteElementString("Party_id", this.updatedValues.Party_id.ToString());
            }
            else if (this.initialValues.Party_idHasValue)
            {
                writer.WriteElementString("Party_id", this.initialValues.Party_id.ToString());
            }

            if (this.updatedValues.Address_idHasValue)
            {
                writer.WriteElementString("Address_id", this.updatedValues.Address_id.ToString());
            }
            else if (this.initialValues.Address_idHasValue)
            {
                writer.WriteElementString("Address_id", this.initialValues.Address_id.ToString());
            }

            this.AfterWriteXml(writer);
        }
    }
}
