//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;
using System.Xml.Linq;
using System.Xml.Serialization;
using Qujck.Pas.Core.Enumerations;
using Qujck.Pas.Model.Policy.DataObjects;

namespace Qujck.Pas.Model.Policy
{
    [Serializable]
    public sealed partial class FundAllocationDetail : AbstractPolicyEntity
    {
        internal FundAllocationDetailDo initialValues { get; private set; }
        internal FundAllocationDetailDo updatedValues { get; private set; }
        internal Action<FundAllocationDetailDo, string> loadMissingValue { private get; set; }

        public FundAllocationDetail()
        {
            this.initialValues = new FundAllocationDetailDo();
            this.updatedValues = new FundAllocationDetailDo();
            this.loadMissingValue = (a, b) => { };
        }

        [XmlIgnore]
        internal override string schema
        {
            get
            {
                return "Policy";
            }
        }

        [XmlIgnore]
        internal override string table
        {
            get
            {
                return "FundAllocationDetail";
            }
        }

        [XmlIgnore]
        internal override IEnumerable<string> columns
        {
            get
            {
                yield return "id";
                yield return "amount";
                yield return "amountPercentage";
                yield return "Fund_code";
                yield return "FundAllocationHeader_id";
            }
        }

        public override long id
        {
            get
            {
                return this.initialValues.id;
            }
            set
            {
                this.initialValues.id = value;
            }
        }

        [XmlElement(ElementName="amount")]
        public decimal? amount 
	    { 
            get
            {
                if (this.updatedValues.amountHasValue)
                {
                    return this.updatedValues.amount;
                }
                
                if (!this.initialValues.amountHasValue)
                {
                    this.loadMissingValue(this.initialValues, "amount");
                    this.initialValues.amountHasValue = true;
                }

                return this.initialValues.amount;
            }
            set
            {
                this.updatedValues.amount = value;
            }
        }

        [XmlElement(ElementName="amountPercentage")]
        public decimal? amountPercentage 
	    { 
            get
            {
                if (this.updatedValues.amountPercentageHasValue)
                {
                    return this.updatedValues.amountPercentage;
                }
                
                if (!this.initialValues.amountPercentageHasValue)
                {
                    this.loadMissingValue(this.initialValues, "amountPercentage");
                    this.initialValues.amountPercentageHasValue = true;
                }

                return this.initialValues.amountPercentage;
            }
            set
            {
                this.updatedValues.amountPercentage = value;
            }
        }

        [StringLength(25)]
        [XmlElement(ElementName="Fund_code")]
        public string Fund_code 
	    { 
            get
            {
                if (this.updatedValues.Fund_codeHasValue)
                {
                    return this.updatedValues.Fund_code;
                }
                
                if (!this.initialValues.Fund_codeHasValue)
                {
                    this.loadMissingValue(this.initialValues, "Fund_code");
                    this.initialValues.Fund_codeHasValue = true;
                }

                return this.initialValues.Fund_code;
            }
            set
            {
                this.updatedValues.Fund_code = value;
            }
        }

        [XmlElement(ElementName="FundAllocationHeader_id")]
        public long FundAllocationHeader_id 
	    { 
            get
            {
                if (this.updatedValues.FundAllocationHeader_idHasValue)
                {
                    return this.updatedValues.FundAllocationHeader_id;
                }
                
                if (!this.initialValues.FundAllocationHeader_idHasValue)
                {
                    this.loadMissingValue(this.initialValues, "FundAllocationHeader_id");
                    this.initialValues.FundAllocationHeader_idHasValue = true;
                }

                return this.initialValues.FundAllocationHeader_id;
            }
            set
            {
                this.updatedValues.FundAllocationHeader_id = value;
            }
        }

        partial void BeforeDeserialize(IQueryable<XElement> elements);
        partial void AfterDeserialize(IQueryable<XElement> elements);

        public override void Deserialize(IQueryable<XElement> elements)
        {
            this.BeforeDeserialize(elements);

            XElement e1 = elements.FirstOrDefault(x => x.Name == "id");
            if (e1 != null)
            {
                this.id = long.Parse(e1.Value);
            }

            XElement e2 = elements.FirstOrDefault(x => x.Name == "amount");
            if (e2 != null)
            {
                this.amount = decimal.Parse(e2.Value);
            }

            XElement e3 = elements.FirstOrDefault(x => x.Name == "amountPercentage");
            if (e3 != null)
            {
                this.amountPercentage = decimal.Parse(e3.Value);
            }

            XElement e4 = elements.FirstOrDefault(x => x.Name == "Fund_code");
            if (e4 != null) 
            {
                this.Fund_code = e4.Value;
            }

            XElement e5 = elements.FirstOrDefault(x => x.Name == "FundAllocationHeader_id");
            if (e5 != null)
            {
                this.FundAllocationHeader_id = long.Parse(e5.Value);
            }

            this.AfterDeserialize(elements);
        }

        partial void BeforeWriteXml(System.Xml.XmlWriter writer);
        partial void AfterWriteXml(System.Xml.XmlWriter writer);

        public override void WriteXml(System.Xml.XmlWriter writer)
        {
            this.BeforeWriteXml(writer);

            writer.WriteElementString("id", this.initialValues.id.ToString());

            if (this.updatedValues.amountHasValue && amount != null)
            {
                writer.WriteElementString("amount", this.updatedValues.amount.ToString());
            }
            else if (this.initialValues.amountHasValue && amount != null)
            {
                writer.WriteElementString("amount", this.initialValues.amount.ToString());
            }

            if (this.updatedValues.amountPercentageHasValue && amountPercentage != null)
            {
                writer.WriteElementString("amountPercentage", this.updatedValues.amountPercentage.ToString());
            }
            else if (this.initialValues.amountPercentageHasValue && amountPercentage != null)
            {
                writer.WriteElementString("amountPercentage", this.initialValues.amountPercentage.ToString());
            }

            if (this.updatedValues.Fund_codeHasValue && !string.IsNullOrEmpty(Fund_code))
            {
                writer.WriteElementString("Fund_code", this.updatedValues.Fund_code);
            }
            else if (this.initialValues.Fund_codeHasValue && !string.IsNullOrEmpty(Fund_code))
            {
                writer.WriteElementString("Fund_code", this.initialValues.Fund_code);
            }

            if (this.updatedValues.FundAllocationHeader_idHasValue)
            {
                writer.WriteElementString("FundAllocationHeader_id", this.updatedValues.FundAllocationHeader_id.ToString());
            }
            else if (this.initialValues.FundAllocationHeader_idHasValue)
            {
                writer.WriteElementString("FundAllocationHeader_id", this.initialValues.FundAllocationHeader_id.ToString());
            }

            this.AfterWriteXml(writer);
        }
    }
}
