//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;
using System.Xml.Linq;
using System.Xml.Serialization;
using Qujck.Pas.Core.Enumerations;
using Qujck.Pas.Model.Standing.DataObjects;

namespace Qujck.Pas.Model.Standing
{
    [Serializable]
    public sealed partial class InvestmentBenefitConfiguration_Fund : AbstractStandingEntity
    {
        internal InvestmentBenefitConfiguration_FundDo initialValues { get; private set; }
        internal InvestmentBenefitConfiguration_FundDo updatedValues { get; private set; }
        internal Action<InvestmentBenefitConfiguration_FundDo, string> loadMissingValue { private get; set; }

        public InvestmentBenefitConfiguration_Fund()
        {
            this.initialValues = new InvestmentBenefitConfiguration_FundDo();
            this.updatedValues = new InvestmentBenefitConfiguration_FundDo();
            this.loadMissingValue = (a, b) => { };
        }

        [XmlIgnore]
        internal override string schema
        {
            get
            {
                return "Standing";
            }
        }

        [XmlIgnore]
        internal override string table
        {
            get
            {
                return "InvestmentBenefitConfiguration_Fund";
            }
        }

        [XmlIgnore]
        internal override IEnumerable<string> columns
        {
            get
            {
                yield return "id";
                yield return "InvestmentBenefitConfiguration_id";
                yield return "Fund_id";
            }
        }

        public override long id
        {
            get
            {
                return this.initialValues.id;
            }
            set
            {
                this.initialValues.id = value;
            }
        }

        [XmlElement(ElementName="InvestmentBenefitConfiguration_id")]
        public long InvestmentBenefitConfiguration_id 
	    { 
            get
            {
                if (this.updatedValues.InvestmentBenefitConfiguration_idHasValue)
                {
                    return this.updatedValues.InvestmentBenefitConfiguration_id;
                }
                
                if (!this.initialValues.InvestmentBenefitConfiguration_idHasValue)
                {
                    this.loadMissingValue(this.initialValues, "InvestmentBenefitConfiguration_id");
                    this.initialValues.InvestmentBenefitConfiguration_idHasValue = true;
                }

                return this.initialValues.InvestmentBenefitConfiguration_id;
            }
            set
            {
                this.updatedValues.InvestmentBenefitConfiguration_id = value;
            }
        }

        [XmlElement(ElementName="Fund_id")]
        public long Fund_id 
	    { 
            get
            {
                if (this.updatedValues.Fund_idHasValue)
                {
                    return this.updatedValues.Fund_id;
                }
                
                if (!this.initialValues.Fund_idHasValue)
                {
                    this.loadMissingValue(this.initialValues, "Fund_id");
                    this.initialValues.Fund_idHasValue = true;
                }

                return this.initialValues.Fund_id;
            }
            set
            {
                this.updatedValues.Fund_id = value;
            }
        }

        public bool FundIsLoaded { get; private set; }
        internal Func<Fund> FundQuery { private get; set; }
        public Fund Fund
        {
            get
            {
                if (this.FundQuery == null)
                {
                    return null;
                }
                else
                {
                    var result = this.FundQuery();
                    if (!this.FundIsLoaded)
                    {
                        this.FundIsLoaded = result != null;
                    }

                    return result;
                }
            }
        }

        public bool InvestmentBenefitConfigurationIsLoaded { get; private set; }
        internal Func<InvestmentBenefitConfiguration> InvestmentBenefitConfigurationQuery { private get; set; }
        public InvestmentBenefitConfiguration InvestmentBenefitConfiguration
        {
            get
            {
                if (this.InvestmentBenefitConfigurationQuery == null)
                {
                    return null;
                }
                else
                {
                    var result = this.InvestmentBenefitConfigurationQuery();
                    if (!this.InvestmentBenefitConfigurationIsLoaded)
                    {
                        this.InvestmentBenefitConfigurationIsLoaded = result != null;
                    }

                    return result;
                }
            }
        }

        partial void BeforeDeserialize(IQueryable<XElement> elements);
        partial void AfterDeserialize(IQueryable<XElement> elements);

        public override void Deserialize(IQueryable<XElement> elements)
        {
            this.BeforeDeserialize(elements);

            XElement e1 = elements.FirstOrDefault(x => x.Name == "id");
            if (e1 != null)
            {
                this.id = long.Parse(e1.Value);
            }

            XElement e2 = elements.FirstOrDefault(x => x.Name == "InvestmentBenefitConfiguration_id");
            if (e2 != null)
            {
                this.InvestmentBenefitConfiguration_id = long.Parse(e2.Value);
            }

            XElement e3 = elements.FirstOrDefault(x => x.Name == "Fund_id");
            if (e3 != null)
            {
                this.Fund_id = long.Parse(e3.Value);
            }

            this.AfterDeserialize(elements);
        }

        partial void BeforeWriteXml(System.Xml.XmlWriter writer);
        partial void AfterWriteXml(System.Xml.XmlWriter writer);

        public override void WriteXml(System.Xml.XmlWriter writer)
        {
            this.BeforeWriteXml(writer);

            writer.WriteElementString("id", this.initialValues.id.ToString());

            if (this.updatedValues.InvestmentBenefitConfiguration_idHasValue)
            {
                writer.WriteElementString("InvestmentBenefitConfiguration_id", this.updatedValues.InvestmentBenefitConfiguration_id.ToString());
            }
            else if (this.initialValues.InvestmentBenefitConfiguration_idHasValue)
            {
                writer.WriteElementString("InvestmentBenefitConfiguration_id", this.initialValues.InvestmentBenefitConfiguration_id.ToString());
            }

            if (this.updatedValues.Fund_idHasValue)
            {
                writer.WriteElementString("Fund_id", this.updatedValues.Fund_id.ToString());
            }
            else if (this.initialValues.Fund_idHasValue)
            {
                writer.WriteElementString("Fund_id", this.initialValues.Fund_id.ToString());
            }

            this.AfterWriteXml(writer);
        }
    }
}
