//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Policy.DataObjects
{
    [Serializable]
    internal sealed partial class MoneyInDo : AbstractModel
    {
        internal MoneyInDo() 
        {
            this.typeValue = new MoneyInType();
            this.frequencyValue = new Frequency();
            this.paymentMethodValue = new PaymentMethod();
        }
        
        public bool typeHasValue { get; internal set; }
        private MoneyInType typeValue  { get; set; }
        public MoneyInType type 
        {
            get
            {
                return this.typeValue;
            }
            internal set
            {
                this.typeHasValue = true;
                this.typeValue = value;
            }
        }

        public bool frequencyHasValue { get; internal set; }
        private Frequency frequencyValue  { get; set; }
        public Frequency frequency 
        {
            get
            {
                return this.frequencyValue;
            }
            internal set
            {
                this.frequencyHasValue = true;
                this.frequencyValue = value;
            }
        }

        public bool amountHasValue { get; internal set; }
        private decimal amountValue  { get; set; }
        public decimal amount 
        {
            get
            {
                return this.amountValue;
            }
            internal set
            {
                this.amountHasValue = true;
                this.amountValue = value;
            }
        }

        public bool paymentMethodHasValue { get; internal set; }
        private PaymentMethod paymentMethodValue  { get; set; }
        public PaymentMethod paymentMethod 
        {
            get
            {
                return this.paymentMethodValue;
            }
            internal set
            {
                this.paymentMethodHasValue = true;
                this.paymentMethodValue = value;
            }
        }

        public bool startDateHasValue { get; internal set; }
        private System.DateTime? startDateValue  { get; set; }
        public System.DateTime? startDate 
        {
            get
            {
                return this.startDateValue;
            }
            internal set
            {
                this.startDateHasValue = true;
                this.startDateValue = value;
            }
        }

        public bool endDateHasValue { get; internal set; }
        private System.DateTime? endDateValue  { get; set; }
        public System.DateTime? endDate 
        {
            get
            {
                return this.endDateValue;
            }
            internal set
            {
                this.endDateHasValue = true;
                this.endDateValue = value;
            }
        }

        public bool nextContributionDateHasValue { get; internal set; }
        private System.DateTime? nextContributionDateValue  { get; set; }
        public System.DateTime? nextContributionDate 
        {
            get
            {
                return this.nextContributionDateValue;
            }
            internal set
            {
                this.nextContributionDateHasValue = true;
                this.nextContributionDateValue = value;
            }
        }

        public bool MoneyInConfiguration_codeHasValue { get; internal set; }
        private string MoneyInConfiguration_codeValue  { get; set; }
        public string MoneyInConfiguration_code 
        {
            get
            {
                return this.MoneyInConfiguration_codeValue;
            }
            internal set
            {
                this.MoneyInConfiguration_codeHasValue = true;
                this.MoneyInConfiguration_codeValue = value;
            }
        }

        public bool FinancialInstitutionAccount_idHasValue { get; internal set; }
        private long? FinancialInstitutionAccount_idValue  { get; set; }
        public long? FinancialInstitutionAccount_id 
        {
            get
            {
                return this.FinancialInstitutionAccount_idValue;
            }
            internal set
            {
                this.FinancialInstitutionAccount_idHasValue = true;
                this.FinancialInstitutionAccount_idValue = value;
            }
        }

        public bool Contract_idHasValue { get; internal set; }
        private long Contract_idValue  { get; set; }
        public long Contract_id 
        {
            get
            {
                return this.Contract_idValue;
            }
            internal set
            {
                this.Contract_idHasValue = true;
                this.Contract_idValue = value;
            }
        }
    }
}
