//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Policy.DataObjects
{
    [Serializable]
    internal sealed partial class ContractDo : AbstractModel
    {
        internal ContractDo() 
        {
        }
        
        public bool startDateHasValue { get; internal set; }
        private System.DateTime? startDateValue  { get; set; }
        public System.DateTime? startDate 
        {
            get
            {
                return this.startDateValue;
            }
            internal set
            {
                this.startDateHasValue = true;
                this.startDateValue = value;
            }
        }

        public bool endDateHasValue { get; internal set; }
        private System.DateTime? endDateValue  { get; set; }
        public System.DateTime? endDate 
        {
            get
            {
                return this.endDateValue;
            }
            internal set
            {
                this.endDateHasValue = true;
                this.endDateValue = value;
            }
        }

        public bool providerQuotationReferenceHasValue { get; internal set; }
        private string providerQuotationReferenceValue  { get; set; }
        public string providerQuotationReference 
        {
            get
            {
                return this.providerQuotationReferenceValue;
            }
            internal set
            {
                this.providerQuotationReferenceHasValue = true;
                this.providerQuotationReferenceValue = value;
            }
        }

        public bool providerReferenceNumberHasValue { get; internal set; }
        private string providerReferenceNumberValue  { get; set; }
        public string providerReferenceNumber 
        {
            get
            {
                return this.providerReferenceNumberValue;
            }
            internal set
            {
                this.providerReferenceNumberHasValue = true;
                this.providerReferenceNumberValue = value;
            }
        }

        public bool typeHasValue { get; internal set; }
        private string typeValue  { get; set; }
        public string type 
        {
            get
            {
                return this.typeValue;
            }
            internal set
            {
                this.typeHasValue = true;
                this.typeValue = value;
            }
        }

        public bool lastStatementDateHasValue { get; internal set; }
        private System.DateTime? lastStatementDateValue  { get; set; }
        public System.DateTime? lastStatementDate 
        {
            get
            {
                return this.lastStatementDateValue;
            }
            internal set
            {
                this.lastStatementDateHasValue = true;
                this.lastStatementDateValue = value;
            }
        }

        public bool lastStatementValueHasValue { get; internal set; }
        private decimal? lastStatementValueValue  { get; set; }
        public decimal? lastStatementValue 
        {
            get
            {
                return this.lastStatementValueValue;
            }
            internal set
            {
                this.lastStatementValueHasValue = true;
                this.lastStatementValueValue = value;
            }
        }

        public bool nextStatementDateHasValue { get; internal set; }
        private System.DateTime? nextStatementDateValue  { get; set; }
        public System.DateTime? nextStatementDate 
        {
            get
            {
                return this.nextStatementDateValue;
            }
            internal set
            {
                this.nextStatementDateHasValue = true;
                this.nextStatementDateValue = value;
            }
        }

        public bool nextFundBasedChargeDateHasValue { get; internal set; }
        private System.DateTime? nextFundBasedChargeDateValue  { get; set; }
        public System.DateTime? nextFundBasedChargeDate 
        {
            get
            {
                return this.nextFundBasedChargeDateValue;
            }
            internal set
            {
                this.nextFundBasedChargeDateHasValue = true;
                this.nextFundBasedChargeDateValue = value;
            }
        }

        public bool nextRiskCoverChargeDateHasValue { get; internal set; }
        private System.DateTime? nextRiskCoverChargeDateValue  { get; set; }
        public System.DateTime? nextRiskCoverChargeDate 
        {
            get
            {
                return this.nextRiskCoverChargeDateValue;
            }
            internal set
            {
                this.nextRiskCoverChargeDateHasValue = true;
                this.nextRiskCoverChargeDateValue = value;
            }
        }

        public bool termInYearsHasValue { get; internal set; }
        private short? termInYearsValue  { get; set; }
        public short? termInYears 
        {
            get
            {
                return this.termInYearsValue;
            }
            internal set
            {
                this.termInYearsHasValue = true;
                this.termInYearsValue = value;
            }
        }

        public bool ProductConfiguration_codeHasValue { get; internal set; }
        private string ProductConfiguration_codeValue  { get; set; }
        public string ProductConfiguration_code 
        {
            get
            {
                return this.ProductConfiguration_codeValue;
            }
            internal set
            {
                this.ProductConfiguration_codeHasValue = true;
                this.ProductConfiguration_codeValue = value;
            }
        }
    }
}
