//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Security.DataObjects
{
    [Serializable]
    internal sealed partial class SecurityUser_SecurityEntitlementDo : AbstractModel
    {
        internal SecurityUser_SecurityEntitlementDo() 
        {
        }
        
        public bool SecurityEntitlement_idHasValue { get; internal set; }
        private long SecurityEntitlement_idValue  { get; set; }
        public long SecurityEntitlement_id 
        {
            get
            {
                return this.SecurityEntitlement_idValue;
            }
            internal set
            {
                this.SecurityEntitlement_idHasValue = true;
                this.SecurityEntitlement_idValue = value;
            }
        }

        public bool SecurityUser_idHasValue { get; internal set; }
        private long SecurityUser_idValue  { get; set; }
        public long SecurityUser_id 
        {
            get
            {
                return this.SecurityUser_idValue;
            }
            internal set
            {
                this.SecurityUser_idHasValue = true;
                this.SecurityUser_idValue = value;
            }
        }
    }
}
