//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Standing.DataObjects
{
    [Serializable]
    internal sealed partial class InstructionConfigurationDo : AbstractModel
    {
        internal InstructionConfigurationDo() 
        {
            this.enabledValue = new Indicator();
            this.requiresPricesValue = new Indicator();
        }
        
        public bool codeHasValue { get; internal set; }
        private string codeValue  { get; set; }
        public string code 
        {
            get
            {
                return this.codeValue;
            }
            internal set
            {
                this.codeHasValue = true;
                this.codeValue = value;
            }
        }

        public bool typeHasValue { get; internal set; }
        private string typeValue  { get; set; }
        public string type 
        {
            get
            {
                return this.typeValue;
            }
            internal set
            {
                this.typeHasValue = true;
                this.typeValue = value;
            }
        }

        public bool sequenceHasValue { get; internal set; }
        private short sequenceValue  { get; set; }
        public short sequence 
        {
            get
            {
                return this.sequenceValue;
            }
            internal set
            {
                this.sequenceHasValue = true;
                this.sequenceValue = value;
            }
        }

        public bool maxDispatchersHasValue { get; internal set; }
        private short maxDispatchersValue  { get; set; }
        public short maxDispatchers 
        {
            get
            {
                return this.maxDispatchersValue;
            }
            internal set
            {
                this.maxDispatchersHasValue = true;
                this.maxDispatchersValue = value;
            }
        }

        public bool maxProcessesHasValue { get; internal set; }
        private short maxProcessesValue  { get; set; }
        public short maxProcesses 
        {
            get
            {
                return this.maxProcessesValue;
            }
            internal set
            {
                this.maxProcessesHasValue = true;
                this.maxProcessesValue = value;
            }
        }

        public bool enabledHasValue { get; internal set; }
        private Indicator enabledValue  { get; set; }
        public Indicator enabled 
        {
            get
            {
                return this.enabledValue;
            }
            internal set
            {
                this.enabledHasValue = true;
                this.enabledValue = value;
            }
        }

        public bool requiresPricesHasValue { get; internal set; }
        private Indicator requiresPricesValue  { get; set; }
        public Indicator requiresPrices 
        {
            get
            {
                return this.requiresPricesValue;
            }
            internal set
            {
                this.requiresPricesHasValue = true;
                this.requiresPricesValue = value;
            }
        }
    }
}
