//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Standing.DataObjects
{
    [Serializable]
    internal sealed partial class DocumentConfigurationDo : AbstractModel
    {
        internal DocumentConfigurationDo() 
        {
            this.archiveRequiredValue = new Indicator();
        }
        
        public bool codeHasValue { get; internal set; }
        private string codeValue  { get; set; }
        public string code 
        {
            get
            {
                return this.codeValue;
            }
            internal set
            {
                this.codeHasValue = true;
                this.codeValue = value;
            }
        }

        public bool archiveRequiredHasValue { get; internal set; }
        private Indicator archiveRequiredValue  { get; set; }
        public Indicator archiveRequired 
        {
            get
            {
                return this.archiveRequiredValue;
            }
            internal set
            {
                this.archiveRequiredHasValue = true;
                this.archiveRequiredValue = value;
            }
        }
    }
}
