//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Standing.DataObjects
{
    [Serializable]
    internal sealed partial class InvestmentBenefitConfigurationDo : AbstractModel
    {
        internal InvestmentBenefitConfigurationDo() 
        {
        }
        
        public bool codeHasValue { get; internal set; }
        private string codeValue  { get; set; }
        public string code 
        {
            get
            {
                return this.codeValue;
            }
            internal set
            {
                this.codeHasValue = true;
                this.codeValue = value;
            }
        }

        public bool typeHasValue { get; internal set; }
        private string typeValue  { get; set; }
        public string type 
        {
            get
            {
                return this.typeValue;
            }
            internal set
            {
                this.typeHasValue = true;
                this.typeValue = value;
            }
        }

        public bool minimumAmountHasValue { get; internal set; }
        private decimal minimumAmountValue  { get; set; }
        public decimal minimumAmount 
        {
            get
            {
                return this.minimumAmountValue;
            }
            internal set
            {
                this.minimumAmountHasValue = true;
                this.minimumAmountValue = value;
            }
        }

        public bool maximumAmountHasValue { get; internal set; }
        private decimal maximumAmountValue  { get; set; }
        public decimal maximumAmount 
        {
            get
            {
                return this.maximumAmountValue;
            }
            internal set
            {
                this.maximumAmountHasValue = true;
                this.maximumAmountValue = value;
            }
        }

        public bool minimumPercentageHasValue { get; internal set; }
        private decimal minimumPercentageValue  { get; set; }
        public decimal minimumPercentage 
        {
            get
            {
                return this.minimumPercentageValue;
            }
            internal set
            {
                this.minimumPercentageHasValue = true;
                this.minimumPercentageValue = value;
            }
        }

        public bool maximumPercentageHasValue { get; internal set; }
        private decimal maximumPercentageValue  { get; set; }
        public decimal maximumPercentage 
        {
            get
            {
                return this.maximumPercentageValue;
            }
            internal set
            {
                this.maximumPercentageHasValue = true;
                this.maximumPercentageValue = value;
            }
        }

        public bool maximumChangePercentageHasValue { get; internal set; }
        private decimal maximumChangePercentageValue  { get; set; }
        public decimal maximumChangePercentage 
        {
            get
            {
                return this.maximumChangePercentageValue;
            }
            internal set
            {
                this.maximumChangePercentageHasValue = true;
                this.maximumChangePercentageValue = value;
            }
        }
    }
}
