//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Interface.DataObjects
{
    [Serializable]
    internal sealed partial class MetaDo : AbstractModel
    {
        internal MetaDo() 
        {
            this.communicationMethodValue = new CommunicationMethod();
            this.archiveRequiredValue = new Indicator();
            this.copyValue = new Indicator();
        }
        
        public bool referenceHasValue { get; internal set; }
        private Guid referenceValue  { get; set; }
        public Guid reference 
        {
            get
            {
                return this.referenceValue;
            }
            internal set
            {
                this.referenceHasValue = true;
                this.referenceValue = value;
            }
        }

        public bool Contract_idHasValue { get; internal set; }
        private long? Contract_idValue  { get; set; }
        public long? Contract_id 
        {
            get
            {
                return this.Contract_idValue;
            }
            internal set
            {
                this.Contract_idHasValue = true;
                this.Contract_idValue = value;
            }
        }

        public bool Party_idHasValue { get; internal set; }
        private long? Party_idValue  { get; set; }
        public long? Party_id 
        {
            get
            {
                return this.Party_idValue;
            }
            internal set
            {
                this.Party_idHasValue = true;
                this.Party_idValue = value;
            }
        }

        public bool dateHasValue { get; internal set; }
        private System.DateTime? dateValue  { get; set; }
        public System.DateTime? date 
        {
            get
            {
                return this.dateValue;
            }
            internal set
            {
                this.dateHasValue = true;
                this.dateValue = value;
            }
        }

        public bool DocumentConfiguration_codeHasValue { get; internal set; }
        private string DocumentConfiguration_codeValue  { get; set; }
        public string DocumentConfiguration_code 
        {
            get
            {
                return this.DocumentConfiguration_codeValue;
            }
            internal set
            {
                this.DocumentConfiguration_codeHasValue = true;
                this.DocumentConfiguration_codeValue = value;
            }
        }

        public bool communicationMethodHasValue { get; internal set; }
        private CommunicationMethod communicationMethodValue  { get; set; }
        public CommunicationMethod communicationMethod 
        {
            get
            {
                return this.communicationMethodValue;
            }
            internal set
            {
                this.communicationMethodHasValue = true;
                this.communicationMethodValue = value;
            }
        }

        public bool archiveRequiredHasValue { get; internal set; }
        private Indicator archiveRequiredValue  { get; set; }
        public Indicator archiveRequired 
        {
            get
            {
                return this.archiveRequiredValue;
            }
            internal set
            {
                this.archiveRequiredHasValue = true;
                this.archiveRequiredValue = value;
            }
        }

        public bool copyHasValue { get; internal set; }
        private Indicator copyValue  { get; set; }
        public Indicator copy 
        {
            get
            {
                return this.copyValue;
            }
            internal set
            {
                this.copyHasValue = true;
                this.copyValue = value;
            }
        }

        public bool LetterWrapper_idHasValue { get; internal set; }
        private long LetterWrapper_idValue  { get; set; }
        public long LetterWrapper_id 
        {
            get
            {
                return this.LetterWrapper_idValue;
            }
            internal set
            {
                this.LetterWrapper_idHasValue = true;
                this.LetterWrapper_idValue = value;
            }
        }
    }
}
