//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Policy.DataObjects
{
    [Serializable]
    internal sealed partial class MonetaryTransactionDo : AbstractModel
    {
        internal MonetaryTransactionDo() 
        {
            this.typeValue = new MonetaryTransactionType();
            this.purchaseStageValue = new PurchaseStage();
        }
        
        public bool amountHasValue { get; internal set; }
        private decimal? amountValue  { get; set; }
        public decimal? amount 
        {
            get
            {
                return this.amountValue;
            }
            internal set
            {
                this.amountHasValue = true;
                this.amountValue = value;
            }
        }

        public bool relevantYearHasValue { get; internal set; }
        private short? relevantYearValue  { get; set; }
        public short? relevantYear 
        {
            get
            {
                return this.relevantYearValue;
            }
            internal set
            {
                this.relevantYearHasValue = true;
                this.relevantYearValue = value;
            }
        }

        public bool referenceNumberHasValue { get; internal set; }
        private string referenceNumberValue  { get; set; }
        public string referenceNumber 
        {
            get
            {
                return this.referenceNumberValue;
            }
            internal set
            {
                this.referenceNumberHasValue = true;
                this.referenceNumberValue = value;
            }
        }

        public bool sourceTypeHasValue { get; internal set; }
        private string sourceTypeValue  { get; set; }
        public string sourceType 
        {
            get
            {
                return this.sourceTypeValue;
            }
            internal set
            {
                this.sourceTypeHasValue = true;
                this.sourceTypeValue = value;
            }
        }

        public bool typeHasValue { get; internal set; }
        private MonetaryTransactionType typeValue  { get; set; }
        public MonetaryTransactionType type 
        {
            get
            {
                return this.typeValue;
            }
            internal set
            {
                this.typeHasValue = true;
                this.typeValue = value;
            }
        }

        public bool purchaseStageHasValue { get; internal set; }
        private PurchaseStage purchaseStageValue  { get; set; }
        public PurchaseStage purchaseStage 
        {
            get
            {
                return this.purchaseStageValue;
            }
            internal set
            {
                this.purchaseStageHasValue = true;
                this.purchaseStageValue = value;
            }
        }

        public bool reasonHasValue { get; internal set; }
        private string reasonValue  { get; set; }
        public string reason 
        {
            get
            {
                return this.reasonValue;
            }
            internal set
            {
                this.reasonHasValue = true;
                this.reasonValue = value;
            }
        }

        public bool dateHasValue { get; internal set; }
        private System.DateTime dateValue  { get; set; }
        public System.DateTime date 
        {
            get
            {
                return this.dateValue;
            }
            internal set
            {
                this.dateHasValue = true;
                this.dateValue = value;
            }
        }

        public bool timeHasValue { get; internal set; }
        private System.TimeSpan? timeValue  { get; set; }
        public System.TimeSpan? time 
        {
            get
            {
                return this.timeValue;
            }
            internal set
            {
                this.timeHasValue = true;
                this.timeValue = value;
            }
        }

        public bool FinancialInstitutionAccount_idHasValue { get; internal set; }
        private long? FinancialInstitutionAccount_idValue  { get; set; }
        public long? FinancialInstitutionAccount_id 
        {
            get
            {
                return this.FinancialInstitutionAccount_idValue;
            }
            internal set
            {
                this.FinancialInstitutionAccount_idHasValue = true;
                this.FinancialInstitutionAccount_idValue = value;
            }
        }

        public bool Contract_idHasValue { get; internal set; }
        private long Contract_idValue  { get; set; }
        public long Contract_id 
        {
            get
            {
                return this.Contract_idValue;
            }
            internal set
            {
                this.Contract_idHasValue = true;
                this.Contract_idValue = value;
            }
        }
    }
}
