//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Policy.DataObjects
{
    [Serializable]
    internal sealed partial class NonMonetaryTransactionDo : AbstractModel
    {
        internal NonMonetaryTransactionDo() 
        {
            this.typeValue = new NonMonetaryTransactionType();
        }
        
        public bool typeHasValue { get; internal set; }
        private NonMonetaryTransactionType typeValue  { get; set; }
        public NonMonetaryTransactionType type 
        {
            get
            {
                return this.typeValue;
            }
            internal set
            {
                this.typeHasValue = true;
                this.typeValue = value;
            }
        }

        public bool dateHasValue { get; internal set; }
        private System.DateTime dateValue  { get; set; }
        public System.DateTime date 
        {
            get
            {
                return this.dateValue;
            }
            internal set
            {
                this.dateHasValue = true;
                this.dateValue = value;
            }
        }

        public bool timeHasValue { get; internal set; }
        private System.TimeSpan? timeValue  { get; set; }
        public System.TimeSpan? time 
        {
            get
            {
                return this.timeValue;
            }
            internal set
            {
                this.timeHasValue = true;
                this.timeValue = value;
            }
        }

        public bool referenceTypeHasValue { get; internal set; }
        private string referenceTypeValue  { get; set; }
        public string referenceType 
        {
            get
            {
                return this.referenceTypeValue;
            }
            internal set
            {
                this.referenceTypeHasValue = true;
                this.referenceTypeValue = value;
            }
        }

        public bool reference_idHasValue { get; internal set; }
        private long reference_idValue  { get; set; }
        public long reference_id 
        {
            get
            {
                return this.reference_idValue;
            }
            internal set
            {
                this.reference_idHasValue = true;
                this.reference_idValue = value;
            }
        }

        public bool Party_idHasValue { get; internal set; }
        private long? Party_idValue  { get; set; }
        public long? Party_id 
        {
            get
            {
                return this.Party_idValue;
            }
            internal set
            {
                this.Party_idHasValue = true;
                this.Party_idValue = value;
            }
        }

        public bool Contract_idHasValue { get; internal set; }
        private long? Contract_idValue  { get; set; }
        public long? Contract_id 
        {
            get
            {
                return this.Contract_idValue;
            }
            internal set
            {
                this.Contract_idHasValue = true;
                this.Contract_idValue = value;
            }
        }
    }
}
