//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Policy.DataObjects
{
    [Serializable]
    internal sealed partial class OrganisationDo : AbstractModel
    {
        internal OrganisationDo() 
        {
        }
        
        public bool nameHasValue { get; internal set; }
        private string nameValue  { get; set; }
        public string name 
        {
            get
            {
                return this.nameValue;
            }
            internal set
            {
                this.nameHasValue = true;
                this.nameValue = value;
            }
        }

        public bool registeredCompanyNumberHasValue { get; internal set; }
        private string registeredCompanyNumberValue  { get; set; }
        public string registeredCompanyNumber 
        {
            get
            {
                return this.registeredCompanyNumberValue;
            }
            internal set
            {
                this.registeredCompanyNumberHasValue = true;
                this.registeredCompanyNumberValue = value;
            }
        }

        public bool fsaReferenceNumberHasValue { get; internal set; }
        private string fsaReferenceNumberValue  { get; set; }
        public string fsaReferenceNumber 
        {
            get
            {
                return this.fsaReferenceNumberValue;
            }
            internal set
            {
                this.fsaReferenceNumberHasValue = true;
                this.fsaReferenceNumberValue = value;
            }
        }

        public bool fsaNameHasValue { get; internal set; }
        private string fsaNameValue  { get; set; }
        public string fsaName 
        {
            get
            {
                return this.fsaNameValue;
            }
            internal set
            {
                this.fsaNameHasValue = true;
                this.fsaNameValue = value;
            }
        }

        public bool Party_idHasValue { get; internal set; }
        private long Party_idValue  { get; set; }
        public long Party_id 
        {
            get
            {
                return this.Party_idValue;
            }
            internal set
            {
                this.Party_idHasValue = true;
                this.Party_idValue = value;
            }
        }
    }
}
