//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Policy.DataObjects
{
    [Serializable]
    internal sealed partial class MaturityDo : AbstractModel
    {
        internal MaturityDo() 
        {
            this.statusValue = new MaturityState();
            this.paymentMethodValue = new PaymentMethod();
        }
        
        public bool effectiveDateHasValue { get; internal set; }
        private System.DateTime effectiveDateValue  { get; set; }
        public System.DateTime effectiveDate 
        {
            get
            {
                return this.effectiveDateValue;
            }
            internal set
            {
                this.effectiveDateHasValue = true;
                this.effectiveDateValue = value;
            }
        }

        public bool statusHasValue { get; internal set; }
        private MaturityState statusValue  { get; set; }
        public MaturityState status 
        {
            get
            {
                return this.statusValue;
            }
            internal set
            {
                this.statusHasValue = true;
                this.statusValue = value;
            }
        }

        public bool numberOfWakeUpLettersHasValue { get; internal set; }
        private short numberOfWakeUpLettersValue  { get; set; }
        public short numberOfWakeUpLetters 
        {
            get
            {
                return this.numberOfWakeUpLettersValue;
            }
            internal set
            {
                this.numberOfWakeUpLettersHasValue = true;
                this.numberOfWakeUpLettersValue = value;
            }
        }

        public bool firstWakeUpLetterDateHasValue { get; internal set; }
        private System.DateTime? firstWakeUpLetterDateValue  { get; set; }
        public System.DateTime? firstWakeUpLetterDate 
        {
            get
            {
                return this.firstWakeUpLetterDateValue;
            }
            internal set
            {
                this.firstWakeUpLetterDateHasValue = true;
                this.firstWakeUpLetterDateValue = value;
            }
        }

        public bool nextWakeUpLetterDateHasValue { get; internal set; }
        private System.DateTime? nextWakeUpLetterDateValue  { get; set; }
        public System.DateTime? nextWakeUpLetterDate 
        {
            get
            {
                return this.nextWakeUpLetterDateValue;
            }
            internal set
            {
                this.nextWakeUpLetterDateHasValue = true;
                this.nextWakeUpLetterDateValue = value;
            }
        }

        public bool paymentMethodHasValue { get; internal set; }
        private PaymentMethod paymentMethodValue  { get; set; }
        public PaymentMethod paymentMethod 
        {
            get
            {
                return this.paymentMethodValue;
            }
            internal set
            {
                this.paymentMethodHasValue = true;
                this.paymentMethodValue = value;
            }
        }

        public bool payeeHasValue { get; internal set; }
        private string payeeValue  { get; set; }
        public string payee 
        {
            get
            {
                return this.payeeValue;
            }
            internal set
            {
                this.payeeHasValue = true;
                this.payeeValue = value;
            }
        }

        public bool FinancialInstitutionAccount_idHasValue { get; internal set; }
        private long? FinancialInstitutionAccount_idValue  { get; set; }
        public long? FinancialInstitutionAccount_id 
        {
            get
            {
                return this.FinancialInstitutionAccount_idValue;
            }
            internal set
            {
                this.FinancialInstitutionAccount_idHasValue = true;
                this.FinancialInstitutionAccount_idValue = value;
            }
        }

        public bool Contract_idHasValue { get; internal set; }
        private long Contract_idValue  { get; set; }
        public long Contract_id 
        {
            get
            {
                return this.Contract_idValue;
            }
            internal set
            {
                this.Contract_idHasValue = true;
                this.Contract_idValue = value;
            }
        }
    }
}
