//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Standing.DataObjects
{
    [Serializable]
    internal sealed partial class FundDo : AbstractModel
    {
        internal FundDo() 
        {
        }
        
        public bool codeHasValue { get; internal set; }
        private string codeValue  { get; set; }
        public string code 
        {
            get
            {
                return this.codeValue;
            }
            internal set
            {
                this.codeHasValue = true;
                this.codeValue = value;
            }
        }

        public bool nameHasValue { get; internal set; }
        private string nameValue  { get; set; }
        public string name 
        {
            get
            {
                return this.nameValue;
            }
            internal set
            {
                this.nameHasValue = true;
                this.nameValue = value;
            }
        }
    }
}
