//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Qujck.Pas.Core.Enumerations;

namespace Qujck.Pas.Model.Standing.DataObjects
{
    [Serializable]
    internal sealed partial class InvestmentBenefitConfiguration_FundDo : AbstractModel
    {
        internal InvestmentBenefitConfiguration_FundDo() 
        {
        }
        
        public bool InvestmentBenefitConfiguration_idHasValue { get; internal set; }
        private long InvestmentBenefitConfiguration_idValue  { get; set; }
        public long InvestmentBenefitConfiguration_id 
        {
            get
            {
                return this.InvestmentBenefitConfiguration_idValue;
            }
            internal set
            {
                this.InvestmentBenefitConfiguration_idHasValue = true;
                this.InvestmentBenefitConfiguration_idValue = value;
            }
        }

        public bool Fund_idHasValue { get; internal set; }
        private long Fund_idValue  { get; set; }
        public long Fund_id 
        {
            get
            {
                return this.Fund_idValue;
            }
            internal set
            {
                this.Fund_idHasValue = true;
                this.Fund_idValue = value;
            }
        }
    }
}
