//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace Qujck.Pas.Core.Enumerations
{
    public sealed class FundUnitHoldingValueType : IEnumeration, IComparable
    {
        #region static
        private static readonly Dictionary<string, FundUnitHoldingValueType> _list = new Dictionary<string, FundUnitHoldingValueType>();

        public static bool Contains(string key)
        {
            return _list.Any(x => x.Key == key);
        }

        public static bool operator !=(FundUnitHoldingValueType a, FundUnitHoldingValueType b)
        {
            return (!a.Equals(b));
        }

        public static bool operator ==(FundUnitHoldingValueType a, FundUnitHoldingValueType b)
        {
            return (a.Equals(b));
        }

		public static implicit operator FundUnitHoldingValueType(string value)
        {
            if (value == null || value.Trim().Length == 0) return FundUnitHoldingValueType.Null;
            if (Contains(value))
                return _list[value];
            else
                throw new InvalidCastException(string.Format("FundUnitHoldingValueType.{0} not found.", value));
        }

        public static implicit operator String(FundUnitHoldingValueType item)
        {
            return item.Value;
        }

        public static readonly FundUnitHoldingValueType Null = new FundUnitHoldingValueType("");
        /// <summary>
        /// 
        /// </summary>
		public static readonly FundUnitHoldingValueType Ntu = new FundUnitHoldingValueType("Ntu");
        /// <summary>
        /// 
        /// </summary>
		public static readonly FundUnitHoldingValueType ReturnOfFund = new FundUnitHoldingValueType("ReturnOfFund");
        /// <summary>
        /// 
        /// </summary>
		public static readonly FundUnitHoldingValueType Surrender = new FundUnitHoldingValueType("Surrender");

        public static IEnumerable<FundUnitHoldingValueType> GetValues()
        {
            yield return Null;
		    yield return Ntu;
		    yield return ReturnOfFund;
		    yield return Surrender;
        }

        #endregion

        #region instance
        private readonly string _value;
        private readonly bool _readonly;
        private FundUnitHoldingValueType _instance;

        private FundUnitHoldingValueType(string value)
        {
            _readonly = true;
            _value = value;
            _instance = this;
            _list[value] = _instance;
        }

		public FundUnitHoldingValueType()
        {
            _readonly = false;
            _instance = FundUnitHoldingValueType.Null;
        }

		[XmlText]
        public string Value
        {
            get
            {
                if (_instance == FundUnitHoldingValueType.Null) return null;
                return _instance._value;
            }
            set
            {
                if (_readonly)
                    throw new InvalidOperationException("Cannot assign a value to an enumeration.");
                if (value == null) _instance = FundUnitHoldingValueType.Null;
                else
                {
                    if (!_list.ContainsKey(value))
                        throw new NullReferenceException(string.Format("FundUnitHoldingValueType.{0} not found.", value));
                    _instance = _list[value];
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            if (this.GetType() != obj.GetType()) return false;

            // safe because of the GetType check
            FundUnitHoldingValueType item = (FundUnitHoldingValueType)obj;

            return System.Object.ReferenceEquals(_instance, item);
        }

        public override int GetHashCode()
        {
			if (_value == null) return "".GetHashCode();
            else return _value.GetHashCode();
        }

        public int CompareTo(object obj)
        {
            if (obj is FundUnitHoldingValueType)
            {
				if (_instance.Value == null)
				{
					if (obj == null) return 0;
					else return -1;
				}
                FundUnitHoldingValueType compare = (FundUnitHoldingValueType)obj;
                return _instance.Value.CompareTo(compare.Value);
            }
            else
                throw new ArgumentException("Object is not a FundUnitHoldingValueType.");
        }
        #endregion
    }
}
