//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace Qujck.Pas.Core.Enumerations
{
    public sealed class InstructionPriority : IEnumeration, IComparable
    {
        #region static
        private static readonly Dictionary<string, InstructionPriority> _list = new Dictionary<string, InstructionPriority>();

        public static bool Contains(string key)
        {
            return _list.Any(x => x.Key == key);
        }

        public static bool operator !=(InstructionPriority a, InstructionPriority b)
        {
            return (!a.Equals(b));
        }

        public static bool operator ==(InstructionPriority a, InstructionPriority b)
        {
            return (a.Equals(b));
        }

		public static implicit operator InstructionPriority(string value)
        {
            if (value == null || value.Trim().Length == 0) return InstructionPriority.Null;
            if (Contains(value))
                return _list[value];
            else
                throw new InvalidCastException(string.Format("InstructionPriority.{0} not found.", value));
        }

        public static implicit operator String(InstructionPriority item)
        {
            return item.Value;
        }

        public static readonly InstructionPriority Null = new InstructionPriority("");
        /// <summary>
        /// Lowest
        /// </summary>
		public static readonly InstructionPriority _0 = new InstructionPriority("0");
        /// <summary>
        /// Very Low
        /// </summary>
		public static readonly InstructionPriority _1 = new InstructionPriority("1");
        /// <summary>
        /// Low
        /// </summary>
		public static readonly InstructionPriority _3 = new InstructionPriority("3");
        /// <summary>
        /// Default
        /// </summary>
		public static readonly InstructionPriority _4 = new InstructionPriority("4");
        /// <summary>
        /// Above Normal
        /// </summary>
		public static readonly InstructionPriority _5 = new InstructionPriority("5");
        /// <summary>
        /// High
        /// </summary>
		public static readonly InstructionPriority _6 = new InstructionPriority("6");
        /// <summary>
        /// Highest
        /// </summary>
		public static readonly InstructionPriority _7 = new InstructionPriority("7");

        public static IEnumerable<InstructionPriority> GetValues()
        {
            yield return Null;
		    yield return _0;
		    yield return _1;
		    yield return _3;
		    yield return _4;
		    yield return _5;
		    yield return _6;
		    yield return _7;
        }

        #endregion

        #region instance
        private readonly string _value;
        private readonly bool _readonly;
        private InstructionPriority _instance;

        private InstructionPriority(string value)
        {
            _readonly = true;
            _value = value;
            _instance = this;
            _list[value] = _instance;
        }

		public InstructionPriority()
        {
            _readonly = false;
            _instance = InstructionPriority.Null;
        }

		[XmlText]
        public string Value
        {
            get
            {
                if (_instance == InstructionPriority.Null) return null;
                return _instance._value;
            }
            set
            {
                if (_readonly)
                    throw new InvalidOperationException("Cannot assign a value to an enumeration.");
                if (value == null) _instance = InstructionPriority.Null;
                else
                {
                    if (!_list.ContainsKey(value))
                        throw new NullReferenceException(string.Format("InstructionPriority.{0} not found.", value));
                    _instance = _list[value];
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            if (this.GetType() != obj.GetType()) return false;

            // safe because of the GetType check
            InstructionPriority item = (InstructionPriority)obj;

            return System.Object.ReferenceEquals(_instance, item);
        }

        public override int GetHashCode()
        {
			if (_value == null) return "".GetHashCode();
            else return _value.GetHashCode();
        }

        public int CompareTo(object obj)
        {
            if (obj is InstructionPriority)
            {
				if (_instance.Value == null)
				{
					if (obj == null) return 0;
					else return -1;
				}
                InstructionPriority compare = (InstructionPriority)obj;
                return _instance.Value.CompareTo(compare.Value);
            }
            else
                throw new ArgumentException("Object is not a InstructionPriority.");
        }
        #endregion
    }
}
