//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace Qujck.Pas.Core.Enumerations
{
    public sealed class NonMonetaryTransactionType : IEnumeration, IComparable
    {
        #region static
        private static readonly Dictionary<string, NonMonetaryTransactionType> _list = new Dictionary<string, NonMonetaryTransactionType>();

        public static bool Contains(string key)
        {
            return _list.Any(x => x.Key == key);
        }

        public static bool operator !=(NonMonetaryTransactionType a, NonMonetaryTransactionType b)
        {
            return (!a.Equals(b));
        }

        public static bool operator ==(NonMonetaryTransactionType a, NonMonetaryTransactionType b)
        {
            return (a.Equals(b));
        }

		public static implicit operator NonMonetaryTransactionType(string value)
        {
            if (value == null || value.Trim().Length == 0) return NonMonetaryTransactionType.Null;
            if (Contains(value))
                return _list[value];
            else
                throw new InvalidCastException(string.Format("NonMonetaryTransactionType.{0} not found.", value));
        }

        public static implicit operator String(NonMonetaryTransactionType item)
        {
            return item.Value;
        }

        public static readonly NonMonetaryTransactionType Null = new NonMonetaryTransactionType("");
        /// <summary>
        /// 
        /// </summary>
		public static readonly NonMonetaryTransactionType ChangeOfAddress = new NonMonetaryTransactionType("ChangeOfAddress");
        /// <summary>
        /// 
        /// </summary>
		public static readonly NonMonetaryTransactionType RegularStatement = new NonMonetaryTransactionType("RegularStatement");

        public static IEnumerable<NonMonetaryTransactionType> GetValues()
        {
            yield return Null;
		    yield return ChangeOfAddress;
		    yield return RegularStatement;
        }

        #endregion

        #region instance
        private readonly string _value;
        private readonly bool _readonly;
        private NonMonetaryTransactionType _instance;

        private NonMonetaryTransactionType(string value)
        {
            _readonly = true;
            _value = value;
            _instance = this;
            _list[value] = _instance;
        }

		public NonMonetaryTransactionType()
        {
            _readonly = false;
            _instance = NonMonetaryTransactionType.Null;
        }

		[XmlText]
        public string Value
        {
            get
            {
                if (_instance == NonMonetaryTransactionType.Null) return null;
                return _instance._value;
            }
            set
            {
                if (_readonly)
                    throw new InvalidOperationException("Cannot assign a value to an enumeration.");
                if (value == null) _instance = NonMonetaryTransactionType.Null;
                else
                {
                    if (!_list.ContainsKey(value))
                        throw new NullReferenceException(string.Format("NonMonetaryTransactionType.{0} not found.", value));
                    _instance = _list[value];
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            if (this.GetType() != obj.GetType()) return false;

            // safe because of the GetType check
            NonMonetaryTransactionType item = (NonMonetaryTransactionType)obj;

            return System.Object.ReferenceEquals(_instance, item);
        }

        public override int GetHashCode()
        {
			if (_value == null) return "".GetHashCode();
            else return _value.GetHashCode();
        }

        public int CompareTo(object obj)
        {
            if (obj is NonMonetaryTransactionType)
            {
				if (_instance.Value == null)
				{
					if (obj == null) return 0;
					else return -1;
				}
                NonMonetaryTransactionType compare = (NonMonetaryTransactionType)obj;
                return _instance.Value.CompareTo(compare.Value);
            }
            else
                throw new ArgumentException("Object is not a NonMonetaryTransactionType.");
        }
        #endregion
    }
}
