//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace Qujck.Pas.Core.Enumerations
{
    public sealed class PartyRoleType : IEnumeration, IComparable
    {
        #region static
        private static readonly Dictionary<string, PartyRoleType> _list = new Dictionary<string, PartyRoleType>();

        public static bool Contains(string key)
        {
            return _list.Any(x => x.Key == key);
        }

        public static bool operator !=(PartyRoleType a, PartyRoleType b)
        {
            return (!a.Equals(b));
        }

        public static bool operator ==(PartyRoleType a, PartyRoleType b)
        {
            return (a.Equals(b));
        }

		public static implicit operator PartyRoleType(string value)
        {
            if (value == null || value.Trim().Length == 0) return PartyRoleType.Null;
            if (Contains(value))
                return _list[value];
            else
                throw new InvalidCastException(string.Format("PartyRoleType.{0} not found.", value));
        }

        public static implicit operator String(PartyRoleType item)
        {
            return item.Value;
        }

        public static readonly PartyRoleType Null = new PartyRoleType("");
        /// <summary>
        /// 
        /// </summary>
		public static readonly PartyRoleType Applicant = new PartyRoleType("Applicant");
        /// <summary>
        /// 
        /// </summary>
		public static readonly PartyRoleType LegalGuardian = new PartyRoleType("LegalGuardian");
        /// <summary>
        /// 
        /// </summary>
		public static readonly PartyRoleType LifeAssured = new PartyRoleType("LifeAssured");
        /// <summary>
        /// 
        /// </summary>
		public static readonly PartyRoleType ThirdParty = new PartyRoleType("ThirdParty");
        /// <summary>
        /// 
        /// </summary>
		public static readonly PartyRoleType Trustee = new PartyRoleType("Trustee");

        public static IEnumerable<PartyRoleType> GetValues()
        {
            yield return Null;
		    yield return Applicant;
		    yield return LegalGuardian;
		    yield return LifeAssured;
		    yield return ThirdParty;
		    yield return Trustee;
        }

        #endregion

        #region instance
        private readonly string _value;
        private readonly bool _readonly;
        private PartyRoleType _instance;

        private PartyRoleType(string value)
        {
            _readonly = true;
            _value = value;
            _instance = this;
            _list[value] = _instance;
        }

		public PartyRoleType()
        {
            _readonly = false;
            _instance = PartyRoleType.Null;
        }

		[XmlText]
        public string Value
        {
            get
            {
                if (_instance == PartyRoleType.Null) return null;
                return _instance._value;
            }
            set
            {
                if (_readonly)
                    throw new InvalidOperationException("Cannot assign a value to an enumeration.");
                if (value == null) _instance = PartyRoleType.Null;
                else
                {
                    if (!_list.ContainsKey(value))
                        throw new NullReferenceException(string.Format("PartyRoleType.{0} not found.", value));
                    _instance = _list[value];
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            if (this.GetType() != obj.GetType()) return false;

            // safe because of the GetType check
            PartyRoleType item = (PartyRoleType)obj;

            return System.Object.ReferenceEquals(_instance, item);
        }

        public override int GetHashCode()
        {
			if (_value == null) return "".GetHashCode();
            else return _value.GetHashCode();
        }

        public int CompareTo(object obj)
        {
            if (obj is PartyRoleType)
            {
				if (_instance.Value == null)
				{
					if (obj == null) return 0;
					else return -1;
				}
                PartyRoleType compare = (PartyRoleType)obj;
                return _instance.Value.CompareTo(compare.Value);
            }
            else
                throw new ArgumentException("Object is not a PartyRoleType.");
        }
        #endregion
    }
}
