//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace Qujck.Pas.Core.Enumerations
{
    public sealed class AbstractionType : IEnumeration, IComparable
    {
        #region static
        private static readonly Dictionary<string, AbstractionType> _list = new Dictionary<string, AbstractionType>();

        public static bool Contains(string key)
        {
            return _list.Any(x => x.Key == key);
        }

        public static bool operator !=(AbstractionType a, AbstractionType b)
        {
            return (!a.Equals(b));
        }

        public static bool operator ==(AbstractionType a, AbstractionType b)
        {
            return (a.Equals(b));
        }

		public static implicit operator AbstractionType(string value)
        {
            if (value == null || value.Trim().Length == 0) return AbstractionType.Null;
            if (Contains(value))
                return _list[value];
            else
                throw new InvalidCastException(string.Format("AbstractionType.{0} not found.", value));
        }

        public static implicit operator String(AbstractionType item)
        {
            return item.Value;
        }

        public static readonly AbstractionType Null = new AbstractionType("");
        /// <summary>
        /// 
        /// </summary>
		public static readonly AbstractionType Element = new AbstractionType("Element");
        /// <summary>
        /// 
        /// </summary>
		public static readonly AbstractionType Visitor = new AbstractionType("Visitor");

        public static IEnumerable<AbstractionType> GetValues()
        {
            yield return Null;
		    yield return Element;
		    yield return Visitor;
        }

        #endregion

        #region instance
        private readonly string _value;
        private readonly bool _readonly;
        private AbstractionType _instance;

        private AbstractionType(string value)
        {
            _readonly = true;
            _value = value;
            _instance = this;
            _list[value] = _instance;
        }

		public AbstractionType()
        {
            _readonly = false;
            _instance = AbstractionType.Null;
        }

		[XmlText]
        public string Value
        {
            get
            {
                if (_instance == AbstractionType.Null) return null;
                return _instance._value;
            }
            set
            {
                if (_readonly)
                    throw new InvalidOperationException("Cannot assign a value to an enumeration.");
                if (value == null) _instance = AbstractionType.Null;
                else
                {
                    if (!_list.ContainsKey(value))
                        throw new NullReferenceException(string.Format("AbstractionType.{0} not found.", value));
                    _instance = _list[value];
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            if (this.GetType() != obj.GetType()) return false;

            // safe because of the GetType check
            AbstractionType item = (AbstractionType)obj;

            return System.Object.ReferenceEquals(_instance, item);
        }

        public override int GetHashCode()
        {
			if (_value == null) return "".GetHashCode();
            else return _value.GetHashCode();
        }

        public int CompareTo(object obj)
        {
            if (obj is AbstractionType)
            {
				if (_instance.Value == null)
				{
					if (obj == null) return 0;
					else return -1;
				}
                AbstractionType compare = (AbstractionType)obj;
                return _instance.Value.CompareTo(compare.Value);
            }
            else
                throw new ArgumentException("Object is not a AbstractionType.");
        }
        #endregion
    }
}
