//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace Qujck.Pas.Core.Enumerations
{
    public sealed class AddressChangeType : IEnumeration, IComparable
    {
        #region static
        private static readonly Dictionary<string, AddressChangeType> _list = new Dictionary<string, AddressChangeType>();

        public static bool Contains(string key)
        {
            return _list.Any(x => x.Key == key);
        }

        public static bool operator !=(AddressChangeType a, AddressChangeType b)
        {
            return (!a.Equals(b));
        }

        public static bool operator ==(AddressChangeType a, AddressChangeType b)
        {
            return (a.Equals(b));
        }

		public static implicit operator AddressChangeType(string value)
        {
            if (value == null || value.Trim().Length == 0) return AddressChangeType.Null;
            if (Contains(value))
                return _list[value];
            else
                throw new InvalidCastException(string.Format("AddressChangeType.{0} not found.", value));
        }

        public static implicit operator String(AddressChangeType item)
        {
            return item.Value;
        }

        public static readonly AddressChangeType Null = new AddressChangeType("");
        /// <summary>
        /// 
        /// </summary>
		public static readonly AddressChangeType A = new AddressChangeType("A");
        /// <summary>
        /// 
        /// </summary>
		public static readonly AddressChangeType B = new AddressChangeType("B");
        /// <summary>
        /// 
        /// </summary>
		public static readonly AddressChangeType C = new AddressChangeType("C");
        /// <summary>
        /// 
        /// </summary>
		public static readonly AddressChangeType D = new AddressChangeType("D");
        /// <summary>
        /// 
        /// </summary>
		public static readonly AddressChangeType E = new AddressChangeType("E");
        /// <summary>
        /// 
        /// </summary>
		public static readonly AddressChangeType F = new AddressChangeType("F");
        /// <summary>
        /// 
        /// </summary>
		public static readonly AddressChangeType G = new AddressChangeType("G");

        public static IEnumerable<AddressChangeType> GetValues()
        {
            yield return Null;
		    yield return A;
		    yield return B;
		    yield return C;
		    yield return D;
		    yield return E;
		    yield return F;
		    yield return G;
        }

        #endregion

        #region instance
        private readonly string _value;
        private readonly bool _readonly;
        private AddressChangeType _instance;

        private AddressChangeType(string value)
        {
            _readonly = true;
            _value = value;
            _instance = this;
            _list[value] = _instance;
        }

		public AddressChangeType()
        {
            _readonly = false;
            _instance = AddressChangeType.Null;
        }

		[XmlText]
        public string Value
        {
            get
            {
                if (_instance == AddressChangeType.Null) return null;
                return _instance._value;
            }
            set
            {
                if (_readonly)
                    throw new InvalidOperationException("Cannot assign a value to an enumeration.");
                if (value == null) _instance = AddressChangeType.Null;
                else
                {
                    if (!_list.ContainsKey(value))
                        throw new NullReferenceException(string.Format("AddressChangeType.{0} not found.", value));
                    _instance = _list[value];
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            if (this.GetType() != obj.GetType()) return false;

            // safe because of the GetType check
            AddressChangeType item = (AddressChangeType)obj;

            return System.Object.ReferenceEquals(_instance, item);
        }

        public override int GetHashCode()
        {
			if (_value == null) return "".GetHashCode();
            else return _value.GetHashCode();
        }

        public int CompareTo(object obj)
        {
            if (obj is AddressChangeType)
            {
				if (_instance.Value == null)
				{
					if (obj == null) return 0;
					else return -1;
				}
                AddressChangeType compare = (AddressChangeType)obj;
                return _instance.Value.CompareTo(compare.Value);
            }
            else
                throw new ArgumentException("Object is not a AddressChangeType.");
        }
        #endregion
    }
}
