//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace Qujck.Pas.Core.Enumerations
{
    public sealed class ChangeIndex : IEnumeration, IComparable
    {
        #region static
        private static readonly Dictionary<string, ChangeIndex> _list = new Dictionary<string, ChangeIndex>();

        public static bool Contains(string key)
        {
            return _list.Any(x => x.Key == key);
        }

        public static bool operator !=(ChangeIndex a, ChangeIndex b)
        {
            return (!a.Equals(b));
        }

        public static bool operator ==(ChangeIndex a, ChangeIndex b)
        {
            return (a.Equals(b));
        }

		public static implicit operator ChangeIndex(string value)
        {
            if (value == null || value.Trim().Length == 0) return ChangeIndex.Null;
            if (Contains(value))
                return _list[value];
            else
                throw new InvalidCastException(string.Format("ChangeIndex.{0} not found.", value));
        }

        public static implicit operator String(ChangeIndex item)
        {
            return item.Value;
        }

        public static readonly ChangeIndex Null = new ChangeIndex("");
        /// <summary>
        /// 
        /// </summary>
		public static readonly ChangeIndex Fixed = new ChangeIndex("Fixed");
        /// <summary>
        /// 
        /// </summary>
		public static readonly ChangeIndex Level = new ChangeIndex("Level");
        /// <summary>
        /// 
        /// </summary>
		public static readonly ChangeIndex LPI = new ChangeIndex("LPI");
        /// <summary>
        /// 
        /// </summary>
		public static readonly ChangeIndex NAEI = new ChangeIndex("NAEI");
        /// <summary>
        /// 
        /// </summary>
		public static readonly ChangeIndex NAEIPlusFixed = new ChangeIndex("NAEIPlusFixed");
        /// <summary>
        /// 
        /// </summary>
		public static readonly ChangeIndex RPI = new ChangeIndex("RPI");
        /// <summary>
        /// 
        /// </summary>
		public static readonly ChangeIndex RPIPlusFixed = new ChangeIndex("RPIPlusFixed");
        /// <summary>
        /// 
        /// </summary>
		public static readonly ChangeIndex SalaryLed = new ChangeIndex("SalaryLed");

        public static IEnumerable<ChangeIndex> GetValues()
        {
            yield return Null;
		    yield return Fixed;
		    yield return Level;
		    yield return LPI;
		    yield return NAEI;
		    yield return NAEIPlusFixed;
		    yield return RPI;
		    yield return RPIPlusFixed;
		    yield return SalaryLed;
        }

        #endregion

        #region instance
        private readonly string _value;
        private readonly bool _readonly;
        private ChangeIndex _instance;

        private ChangeIndex(string value)
        {
            _readonly = true;
            _value = value;
            _instance = this;
            _list[value] = _instance;
        }

		public ChangeIndex()
        {
            _readonly = false;
            _instance = ChangeIndex.Null;
        }

		[XmlText]
        public string Value
        {
            get
            {
                if (_instance == ChangeIndex.Null) return null;
                return _instance._value;
            }
            set
            {
                if (_readonly)
                    throw new InvalidOperationException("Cannot assign a value to an enumeration.");
                if (value == null) _instance = ChangeIndex.Null;
                else
                {
                    if (!_list.ContainsKey(value))
                        throw new NullReferenceException(string.Format("ChangeIndex.{0} not found.", value));
                    _instance = _list[value];
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            if (this.GetType() != obj.GetType()) return false;

            // safe because of the GetType check
            ChangeIndex item = (ChangeIndex)obj;

            return System.Object.ReferenceEquals(_instance, item);
        }

        public override int GetHashCode()
        {
			if (_value == null) return "".GetHashCode();
            else return _value.GetHashCode();
        }

        public int CompareTo(object obj)
        {
            if (obj is ChangeIndex)
            {
				if (_instance.Value == null)
				{
					if (obj == null) return 0;
					else return -1;
				}
                ChangeIndex compare = (ChangeIndex)obj;
                return _instance.Value.CompareTo(compare.Value);
            }
            else
                throw new ArgumentException("Object is not a ChangeIndex.");
        }
        #endregion
    }
}
