//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace Qujck.Pas.Core.Enumerations
{
    public sealed class SexType : IEnumeration, IComparable
    {
        #region static
        private static readonly Dictionary<string, SexType> _list = new Dictionary<string, SexType>();

        public static bool Contains(string key)
        {
            return _list.Any(x => x.Key == key);
        }

        public static bool operator !=(SexType a, SexType b)
        {
            return (!a.Equals(b));
        }

        public static bool operator ==(SexType a, SexType b)
        {
            return (a.Equals(b));
        }

		public static implicit operator SexType(string value)
        {
            if (value == null || value.Trim().Length == 0) return SexType.Null;
            if (Contains(value))
                return _list[value];
            else
                throw new InvalidCastException(string.Format("SexType.{0} not found.", value));
        }

        public static implicit operator String(SexType item)
        {
            return item.Value;
        }

        public static readonly SexType Null = new SexType("");
        /// <summary>
        /// 
        /// </summary>
		public static readonly SexType Female = new SexType("Female");
        /// <summary>
        /// 
        /// </summary>
		public static readonly SexType Male = new SexType("Male");
        /// <summary>
        /// 
        /// </summary>
		public static readonly SexType Unknown = new SexType("Unknown");

        public static IEnumerable<SexType> GetValues()
        {
            yield return Null;
		    yield return Female;
		    yield return Male;
		    yield return Unknown;
        }

        #endregion

        #region instance
        private readonly string _value;
        private readonly bool _readonly;
        private SexType _instance;

        private SexType(string value)
        {
            _readonly = true;
            _value = value;
            _instance = this;
            _list[value] = _instance;
        }

		public SexType()
        {
            _readonly = false;
            _instance = SexType.Null;
        }

		[XmlText]
        public string Value
        {
            get
            {
                if (_instance == SexType.Null) return null;
                return _instance._value;
            }
            set
            {
                if (_readonly)
                    throw new InvalidOperationException("Cannot assign a value to an enumeration.");
                if (value == null) _instance = SexType.Null;
                else
                {
                    if (!_list.ContainsKey(value))
                        throw new NullReferenceException(string.Format("SexType.{0} not found.", value));
                    _instance = _list[value];
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            if (this.GetType() != obj.GetType()) return false;

            // safe because of the GetType check
            SexType item = (SexType)obj;

            return System.Object.ReferenceEquals(_instance, item);
        }

        public override int GetHashCode()
        {
			if (_value == null) return "".GetHashCode();
            else return _value.GetHashCode();
        }

        public int CompareTo(object obj)
        {
            if (obj is SexType)
            {
				if (_instance.Value == null)
				{
					if (obj == null) return 0;
					else return -1;
				}
                SexType compare = (SexType)obj;
                return _instance.Value.CompareTo(compare.Value);
            }
            else
                throw new ArgumentException("Object is not a SexType.");
        }
        #endregion
    }
}
